package com.tridato.service;

import com.google.gson.Gson;
import com.tridato.service.Response.ResponseAguasCalientes;
import com.tridato.service.entities.Acuerdo;
import com.tridato.service.entities.AcuerdoRepository;
import com.trudato.commons.api.ApiResponse;
import com.trudato.commons.util.Api;
import com.trudato.commons.util.ResponseTridato;
import org.hibernate.Criteria;
import org.hibernate.criterion.Restrictions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;
import java.util.List;
import java.util.concurrent.TimeUnit;

import okhttp3.*;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.criteria.CriteriaBuilder;

@RestController
public class AguasCalientesService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AcuerdoRepository acuerdoRepository;
    @PersistenceContext
    private EntityManager em;

    @RequestMapping(path = "/get/{curp}", produces = "application/json")
    public String get( @PathVariable("curp") final String curp ){
        System.out.println("Ingresando a get");
        //Busco en la bd ese nombres
        List<Acuerdo> acuerdos = em.createNativeQuery("SELECT * from aguascalientes_acuerdos where partes like '"+curp+"'").getResultList();
        if(acuerdos.size()>0){
            //return ResponseEntity.ok();
            return ResponseTridato.fail(1,"Se encontro información", acuerdos.size()+"");
        }else{
            return ResponseTridato.ok(1,"Validado","");
        }


    }
}
